#!/bin/bash
# Entrypoint script for Project Zomboid Docker container
# Handles server installation, updates, configuration, and startup

set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Log function
log() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1"
}

log_error() {
    echo -e "${RED}[$(date +'%Y-%m-%d %H:%M:%S')] ERROR:${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[$(date +'%Y-%m-%d %H:%M:%S')] WARNING:${NC} $1"
}

# Set default environment variables if not provided
export SERVER_NAME="${SERVER_NAME:-My Project Zomboid Server}"
export ADMIN_PASSWORD="${ADMIN_PASSWORD:-changeme}"
export MAX_PLAYERS="${MAX_PLAYERS:-16}"
export SERVER_PUBLIC="${SERVER_PUBLIC:-false}"
export PAUSE_EMPTY="${PAUSE_EMPTY:-true}"
export AUTO_UPDATE="${AUTO_UPDATE:-true}"
export MEMORY="${MEMORY:-4096m}"
export SERVER_PORT="${SERVER_PORT:-16261}"

# Box64 environment variables for optimal performance on ARM64
export BOX64_LOG=0
export BOX64_NOBANNER=1
export BOX64_DYNAREC_BIGBLOCK=1
export BOX64_DYNAREC_STRONGMEM=1
export BOX64_DYNAREC_FASTNAN=0
export BOX64_DYNAREC_FASTROUND=0
export BOX64_DYNAREC_SAFEFLAGS=0
export BOX64_DYNAREC_X87DOUBLE=1
export BOX86_LOG=0
export BOX86_NOBANNER=1

# Paths
STEAMCMD_DIR="/home/steamcmd/steamcmd"
SERVER_DIR="/home/steamcmd/server"
CONFIG_DIR="/home/steamcmd/config"
SAVES_DIR="/home/steamcmd/Zomboid"
LOGS_DIR="/home/steamcmd/logs"

log "Starting Project Zomboid Dedicated Server for ARM64"
log "Using Box64 for x86_64 emulation"

# Verify Java installation
if ! command -v java &> /dev/null; then
    log_error "Java not found!"
    exit 1
fi

log "Java version: $(java -version 2>&1 | head -n 1)"

# Check if server is installed
if [ ! -f "${SERVER_DIR}/ProjectZomboid64.json" ] && [ ! -f "${SERVER_DIR}/start-server.sh" ]; then
    log "Server files not found. Installing Project Zomboid server..."
    /home/steamcmd/install-server.sh
else
    log "Server files found."
    
    # Run update if AUTO_UPDATE is enabled
    if [ "${AUTO_UPDATE}" = "true" ]; then
        log "AUTO_UPDATE is enabled. Checking for updates..."
        /home/steamcmd/update-server.sh
    else
        log "AUTO_UPDATE is disabled. Skipping update check."
    fi
fi

# Ensure config directory exists
mkdir -p "${CONFIG_DIR}"
mkdir -p "${SAVES_DIR}/Server"

# Create or update server configuration
SERVER_INI="${SAVES_DIR}/Server/${SERVER_NAME}.ini"
if [ ! -f "${SERVER_INI}" ]; then
    log "Creating default server configuration..."
    
    # Copy example config if it exists
    if [ -f "${CONFIG_DIR}/server.ini.example" ]; then
        cp "${CONFIG_DIR}/server.ini.example" "${SERVER_INI}"
    else
        # Create basic server.ini
        cat > "${SERVER_INI}" <<EOF
# Project Zomboid Server Configuration
# Auto-generated by Docker container

PVP=true
PauseEmpty=${PAUSE_EMPTY}
GlobalChat=true
Open=true
ServerWelcomeMessage=Welcome to ${SERVER_NAME}!
AutoCreateUserInWhiteList=false
DisplayUserName=true
ShowFirstAndLastName=false
SpawnPoint=0,0,0
SafetySystem=true
ShowSafety=true
SafetyToggleTimer=2
SafetyCooldownTimer=3
SpawnItems=
DefaultPort=${SERVER_PORT}
UDPPort=$((${SERVER_PORT:-16261} + 1))
ResetID=$((RANDOM * RANDOM % 9000000 + 1000000))
Mods=${MODS}
Map=Muldraugh, KY
DoLuaChecksum=true
DenyLoginOnOverloadedServer=true
Public=${SERVER_PUBLIC}
PublicName=${SERVER_NAME}
PublicDescription=
MaxPlayers=${MAX_PLAYERS}
PingLimit=400
HoursForLootRespawn=0
MaxItemsForLootRespawn=4
ConstructionPreventsLootRespawn=true
DropOffWhiteListAfterDeath=false
NoFire=false
AnnounceDeath=true
MinutesPerPage=1.0
SaveWorldEveryMinutes=0
PlayerSafehouse=false
AdminSafehouse=false
SafehouseAllowTrepass=true
SafehouseAllowFire=true
SafehouseAllowLoot=true
SafehouseAllowRespawn=false
SafehouseDaySurvivedToClaim=0
SafeHouseRemovalTime=144
SafehouseAllowNonResidential=false
AllowDestructionBySledgehammer=true
SledgehammerOnlyInSafehouse=false
KickFastPlayers=false
ServerPlayerID=
RCONPort=27015
RCONPassword=
Password=${SERVER_PASSWORD}
MaxAccountsPerUser=0
AllowCoop=true
SleepAllowed=false
SleepNeeded=false
KnockedDownAllowed=true
SneakModeHideFromOtherPlayers=true
WorkshopItems=${WORKSHOP_ITEMS}
SteamScoreboard=true
SteamVAC=true
UPnP=true
VoiceEnable=true
VoiceMinDistance=10.0
VoiceMaxDistance=100.0
Voice3D=true
SpeedLimit=70.0
LoginQueueEnabled=false
LoginQueueConnectTimeout=60
server_browser_announced_ip=
PlayerRespawnWithSelf=false
PlayerRespawnWithOther=false
FastForwardMultiplier=40.0
DisableSafehouseWhenPlayerConnected=false
Faction=true
FactionDaySurvivedToCreate=0
FactionPlayersRequiredForTag=1
DisableRadioStaff=false
DisableRadioAdmin=true
DisableRadioGM=true
DisableRadioOverseer=false
DisableRadioModerator=false
DisableRadioInvisible=true
ClientCommandFilter=-vehicle.*;+vehicle.damageWindow;+vehicle.fixPart;+vehicle.installPart;+vehicle.uninstallPart
ClientActionLogs=ISEnterVehicle;ISExitVehicle;ISTakeEngineParts;
PerkLogs=true
ItemNumbersLimitPerContainer=0
BloodSplatLifespanDays=0
AllowNonAsciiUsername=false
BanKickGlobalSound=true
RemovePlayerCorpsesOnCorpseRemoval=false
TrashDeleteAll=false
PVPMeleeWhileHitReaction=false
MouseOverToSeeDisplayName=true
HidePlayersBehindYou=true
PVPMeleeDamageModifier=30.0
PVPFirearmDamageModifier=50.0
CarEngineAttractionModifier=0.5
PlayerBumpPlayer=false
MapRemotePlayerVisibility=1
BackupsCount=5
BackupsOnStart=true
BackupsOnVersionChange=true
BackupsPeriod=0
EOF
    fi
    
    log "Server configuration created at: ${SERVER_INI}"
else
    log "Using existing server configuration at: ${SERVER_INI}"
fi

# Set admin password
if [ -n "${ADMIN_PASSWORD}" ] && [ "${ADMIN_PASSWORD}" != "changeme" ]; then
    log "Setting admin password..."
    mkdir -p "${SAVES_DIR}/Server"
    # Create admin user (username: admin)
    echo "admin:${ADMIN_PASSWORD}" > "${SAVES_DIR}/Server/${SERVER_NAME}_adminpassword.txt"
fi

# Prepare log file
LOG_FILE="${LOGS_DIR}/server.log"
mkdir -p "${LOGS_DIR}"
touch "${LOG_FILE}"

log "Starting Project Zomboid server..."
log "Server Name: ${SERVER_NAME}"
log "Max Players: ${MAX_PLAYERS}"
log "Public: ${SERVER_PUBLIC}"
log "Port: ${SERVER_PORT}"
log "Memory: ${MEMORY}"

# Change to server directory
cd "${SERVER_DIR}"

# Graceful shutdown handler
shutdown() {
    log "Shutting down server gracefully..."
    if [ -n "$SERVER_PID" ]; then
        kill -SIGTERM "$SERVER_PID" 2>/dev/null || true
        wait "$SERVER_PID" 2>/dev/null || true
    fi
    log "Server stopped."
    exit 0
}

trap shutdown SIGTERM SIGINT

# Start the server using Box64
# The server uses start-server.sh which internally calls the Java server
if [ -f "${SERVER_DIR}/start-server.sh" ]; then
    log "Using start-server.sh to launch server..."
    
    # Make start-server.sh executable
    chmod +x "${SERVER_DIR}/start-server.sh"
    
    # Project Zomboid's start-server.sh is a bash script
    # Box64 will automatically intercept any x86_64 binaries via binfmt
    # Use exec to replace the shell process for proper signal handling
    exec bash "${SERVER_DIR}/start-server.sh" \
        -servername "${SERVER_NAME}" \
        -cachedir=/home/steamcmd/Zomboid \
        -adminusername admin \
        -adminpassword "${ADMIN_PASSWORD}" \
        -Xmx${MEMORY} -Xms${MEMORY} 2>&1 | tee -a "${LOG_FILE}"
else
    log_error "start-server.sh not found in ${SERVER_DIR}"
    log_error "Server installation may be incomplete."
    exit 1
fi
